host        =   'suryani.dev.rf29.net'
pkey        =   'C:/Users/ben.zhuang/.ssh/id_rsa'
pwd         =   '850202'
user        =   'devuser'
remote_git  =   '/var/refinery29'
local_git   =   'd:/php/refinery29'